CREATE TABLE PRODUCTS (
	P_NO NUMBER PRIMARY KEY,
	P_NAME VARCHAR2(100),
	P_PRICE NUMBER,
	P_CONTENT VARCHAR2(500),
	P_STOCK NUMBER,
	P_CATEGORY NUMBER
);

CREATE SEQUENCE PRODUCTS_P_NO START WITH 1 INCREMENT BY 1;

INSERT INTO PRODUCTS 
	VALUES (PRODUCTS_P_NO.NEXTVAL, '빼빼로', '1000', '맛있는 빼빼로', '2', '1');
INSERT INTO PRODUCTS 
	VALUES (PRODUCTS_P_NO.NEXTVAL, '사과', '700', '맛있는 사과', '10', '1');
INSERT INTO PRODUCTS 
	VALUES (PRODUCTS_P_NO.NEXTVAL, '마라소스', '3400', '맛있는 마라소스', '7', '1');
INSERT INTO PRODUCTS 
	VALUES (PRODUCTS_P_NO.NEXTVAL, '의자', '15900', '튼튼한 의자', '11', '2');
INSERT INTO PRODUCTS 
	VALUES (PRODUCTS_P_NO.NEXTVAL, '책꽂이', '45900', '튼튼한 책꽂이', '40', '2');
INSERT INTO PRODUCTS 
	VALUES (PRODUCTS_P_NO.NEXTVAL, '책상', '29800', '튼튼한 책상', '7', '2');
INSERT INTO PRODUCTS 
	VALUES (PRODUCTS_P_NO.NEXTVAL, '마우스', '5000', '무소음 마우스', '23', '3');
INSERT INTO PRODUCTS 
	VALUES (PRODUCTS_P_NO.NEXTVAL, '키보드', '56900', '무소음 키보드', '11', '3');
INSERT INTO PRODUCTS 
	VALUES (PRODUCTS_P_NO.NEXTVAL, '이어폰', '65000', '무선 이어폰', '12', '3');

SELECT *
	FROM PRODUCTS ;

SELECT P_NO , P_NAME , P_PRICE , P_CONTENT , P_STOCK 
	FROM PRODUCTS p 
	WHERE P_CATEGORY = '1';


